### ISSUE TITLE
Installation via composer, Requirements could not be resolved

### ISSUE THREAD

**Issue by luislaborda** [ldaptools/ldaptools-bundle#10]
Trying to install ldaptools via composer however is failing:

Error Message: 
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - ldaptools/ldaptools v0.23.0 requires php >=5.6 -> your PHP version (5.6.25) overridden by "config.platform.php" version (5.5.9) does not satisfy that requirement.
    - ldaptools/ldaptools-bundle 0.6.0 requires ldaptools/ldaptools >=0.23 -> satisfiable by ldaptools/ldaptools[v0.23.0].
    - Installation request for ldaptools/ldaptools-bundle ^0.6.0 -> satisfiable by ldaptools/ldaptools-bundle[0.6.0].

What requirement is failing?

**Comment by luislaborda** [comment]
My bad. I overlook the composer.json which specifies a lower version of PHP

**Comment by ChadSikorra** [comment]
The issue is actually caused by the way the Symfony Standard Distribution has its composer.json setup: https://github.com/symfony/symfony-standard/issues/858. If you install Symfony via the Symfony Installer it strips the composer.json section that causes the issue. However, installing from composer it does not. Basically you have to remove the following from the default Symfony composer file:

```yaml
"config": {
        "platform": {
            "php": "5.5.9"
        }
},
```
