### ISSUE TITLE
ldap_tools_bundle.login.success

### ISSUE THREAD

**Issue by jakobeissler** [ldaptools/ldaptools-bundle#3]
Hello,
I'm having a hard time to implement the "ldap_tools_bundle.login.success" event in services.yml.

What I have done is:

app.ldap_login_listener:
        class: Some\AppBundle\EventListener\LdapLoginListener
        tags:
            - { name: ldap_tools_bundle.event_listener, event: ldap_tools_bundle.login.success, method: onLdapLoginSuccess }

I just won't work. I'm sure I'm missing something.

**Comment by ChadSikorra** [comment]
You want your tag to be like:

```
- { name: kernel.event_listener, event: ldap_tools_bundle.login.success, method: onLdapLoginSuccess }
```

The login success event uses a custom Symfony event, so you need to tag it to the kernel event listener. The LdapTools library has its own event system for its specific events, which is why those need to be tagged with name `name: ldap_tools.event_listener`.

I'll keep this open for the moment and update the docs later tonight with some more information [here](https://github.com/ldaptools/ldaptools-bundle/blob/master/Resources/doc/LDAP-Authentication-Provider.md#successful-login-event).

**Comment by jakobeissler** [comment]
Thank You, that worked. Sorry I'm still pretty new to Symfony. Awesome work.

**Comment by ChadSikorra** [comment]
I've updated the docs with some more complete information via this commit: https://github.com/ldaptools/ldaptools-bundle/commit/d4de2e9d76b7f0b5ef9f1352c879a9856c186e2b. Thanks for reporting this, and I'm glad you found this bundle useful!
