### ISSUE TITLE
LdapUser constructor gets in the way

### ISSUE THREAD

**Issue by natelenart** [ldaptools/ldaptools-bundle#7]
Thanks for the last fix on the doctrine connections, worked great.  Next issue - forcing user objects to use your constructor, which requires the first element to be an instance of LdapObject.  My situation is that I've created a custom UserProvider that attempts to do a 'findOrCreate', by either fetching the object from the database or instantiating a new one, prior to authentication.  The idea was that I would create a new user object in memory, then if it passes authentication, hook into the login success event and flush the new user object into my database.  But, because of the constructor requirement, I had to modify my existing user constructor to pass arguments through, which allowed me to use a custom User object and provider while logging in as a user with an existing account (Doctrine instantiations bypass the constructor), but still will not work for new accounts as I don't have access to an LdapObject to insert into the constructor at this point.  As it stands, I think I could get around this by doing tricks that Doctrine uses, such as reflection or instantiation from serialization, which I'd like to avoid.  I'm thinking that altering the LdapUser object by moving the constructor arguments into setter(s), would both solve my problem, and make inheriting user classes cleaner/easier.  What are your thoughts on this?

**Comment by natelenart** [comment]
FYI, tested this out, works as expected, but not ideal:

```
$refl = new \ReflectionClass($this->user_class);
$user = $refl->newInstanceWithoutConstructor(); 
```

**Comment by ChadSikorra** [comment]
Yep, this bugged me while I was originally setting this bundle up. But I was only using the LdapUserProvider so I never really had the ambition to fix it. I should get rid of the need for the constructor completely for the user class. I'll have to think about how to best do this. Busier than usual this week unfortunately, but hopefully I'll find the time to get to it.

**Comment by natelenart** [comment]
Sounds great, thanks.  No rush on that.  I'm still experimenting and can get by with the ReflectionClass for now.  My code is still WAY cleaner by using this bundle than the convoluted mess I had before.  Thanks!

**Comment by ChadSikorra** [comment]
No problem, glad to hear it's helping out! My current plan to get rid of the need for the constructor is to create an interface called `LdapUserInterface`, which would need the following methods:

```
interface LdapUserInterface
{
    public function setUsername($username);

    public function setLdapGuid($guid);

    public function getLdapGuid();

    public function setRoles(array $roles);

    public function addRole($role);
}
```

The `addRole` and `setRoles` methods are defaults on the normal FOSUserBundle model (which is where this would probably come in most handy). The GUID is needed to ensure future lookups grab the correct user again.

If the user also happens to be an instance of `LdapObject` from the LdapTools bundle then I will call the `refresh()` method with all the attributes that were selected from LDAP. The only thing I'm not sure of yet is how to handle AdvancedUserInterface support.

Do you feel like the above would help you get around the issues you're experiencing a little better?

**Comment by ChadSikorra** [comment]
Fixed by https://github.com/ldaptools/ldaptools-bundle/commit/550fffcc52accb75c72ee8623d98a6a6b583f076. The LdapUserProvider now requires that the user class implement `LdapUserInterface`. It is the above interface mentioned, minus the need for `addRole($role)`. The constructor for the base class now has no constructor arguments.

I also added an additional method for the after user load event called `getLdapObject()`, which will return the LdapTools LDAP object that was used to construct the user class, which I figure might be helpful in some cases. There's an [example in the docs](https://github.com/ldaptools/ldaptools-bundle/blob/master/Resources/doc/LDAP-Authentication-Provider.md#load-user-events).

However, I did get rid of the LDAP attribute mappings configuration options. Instead you should override the default class or define the mappings in the LdapTools schema, as explained [here](https://github.com/ldaptools/ldaptools-bundle/blob/master/Resources/doc/LDAP-Authentication-Provider.md#mapping-ldap-attributes).
